name: Deploy to Vercel

on:
  push:
    branches:
      - main   # 或者您使用的主分支

jobs:
  vercel-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Vercel CLI
        run: |
          npm install -g vercel

      - name: Deploy to Vercel
        run: |
          vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --yes
